"""Hardcoded Node 4-7 classification fine-tuning demo.

Purpose:
- Show the full post-dataset flow in one easy-to-read file.
- Run a classification-only QLoRA fine-tune on Vast.ai with Unsloth.
- Use Phase 1-3 artifacts already generated by this repo.
- Save adapter, tokenizer, metrics, predictions, and a compact run report.

Install on a fresh Vast.ai machine before running:
    pip install unsloth trl transformers datasets accelerate bitsandbytes scikit-learn pandas

Run:
    python fine_tuning_hardcode.py

This intentionally does not include OpenWebUI, Ollama, GGUF export, or OpenRouter.
"""

from __future__ import annotations

import inspect
import json
import math
import os
import re
import sys
import time
import traceback
from pathlib import Path
from typing import Any


# =============================================================================
# Hardcoded Node 4 config
# =============================================================================

RUN_ID = "demo-thai-classification-auto-001"
RUN_DIR = Path("runs") / RUN_ID
INPUT_DIR = RUN_DIR / "input"
OUTPUT_DIR = RUN_DIR / "fine_tuning_hardcode_qwen3_4b"
LOG_DIR = OUTPUT_DIR / "logs"

TRAIN_JSONL = INPUT_DIR / "train.jsonl"
VALIDATION_JSONL = INPUT_DIR / "validation.jsonl"
TEST_JSONL = INPUT_DIR / "test.jsonl"
PROMPT_TEMPLATE_JSON = INPUT_DIR / "classification_prompt_template.json"

MODEL_ID = "unsloth/Qwen3-4B"
MAX_SEQ_LENGTH = 2048
LOAD_IN_4BIT = True

LORA_RANK = 16
LORA_ALPHA = 16
LORA_DROPOUT = 0.05
LORA_TARGET_MODULES = [
    "q_proj",
    "k_proj",
    "v_proj",
    "o_proj",
    "gate_proj",
    "up_proj",
    "down_proj",
]

PER_DEVICE_TRAIN_BATCH_SIZE = 2
PER_DEVICE_EVAL_BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 4
LEARNING_RATE = 1e-4
NUM_TRAIN_EPOCHS = 1

# Vast.ai smoke setting: keep this finite for first verification.
# Set to None after the smoke run if you want a full epoch.
MAX_STEPS = 80

WARMUP_STEPS = 10
WEIGHT_DECAY = 0.05
LR_SCHEDULER_TYPE = "linear"
OPTIM = "adamw_8bit"
SEED = 3407
LOGGING_STEPS = 1
EVAL_STEPS = 25
SAVE_STEPS = 25

# Keep evaluation bounded for a first Vast smoke run.
# Set to None to evaluate all test records.
MAX_TEST_RECORDS = 100


def main() -> None:
    started_at = time.time()
    output_paths = make_output_dirs()
    validate_inputs()

    print("=== Node 4: hardcoded hyperparameter config ===")
    config = build_hardcoded_config()
    write_json(output_paths["config"], config)
    print(json.dumps(config, ensure_ascii=False, indent=2))

    print("\n=== Loading training libraries ===")
    FastLanguageModel, Dataset, SFTConfig, SFTTrainer, DataCollatorForSeq2Seq = import_training_libs()
    from unsloth.chat_templates import train_on_responses_only

    print("\n=== Loading model/tokenizer ===")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=MODEL_ID,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,
        load_in_4bit=LOAD_IN_4BIT,
    )
    model = FastLanguageModel.get_peft_model(
        model,
        r=LORA_RANK,
        target_modules=LORA_TARGET_MODULES,
        lora_alpha=LORA_ALPHA,
        lora_dropout=LORA_DROPOUT,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=SEED,
        use_rslora=False,
        loftq_config=None,
    )

    print("\n=== Loading Phase 1-3 SFT artifacts ===")
    prompt_artifact = read_json(PROMPT_TEMPLATE_JSON)
    labels = prompt_artifact["labels"]
    train_records = read_jsonl(TRAIN_JSONL)
    validation_records = read_jsonl(VALIDATION_JSONL)
    test_records = read_jsonl(TEST_JSONL)
    if MAX_TEST_RECORDS is not None:
        test_records = test_records[:MAX_TEST_RECORDS]
    print(
        f"records: train={len(train_records)}, validation={len(validation_records)}, "
        f"test_for_metrics={len(test_records)}"
    )
    print(f"labels: {labels}")

    train_dataset = Dataset.from_list(to_text_rows(train_records, tokenizer))
    validation_dataset = Dataset.from_list(to_text_rows(validation_records, tokenizer))

    print("\n=== Node 5: SLM fine-tuning ===")
    trainer = build_trainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=train_dataset,
        validation_dataset=validation_dataset,
        SFTConfig=SFTConfig,
        SFTTrainer=SFTTrainer,
        DataCollatorForSeq2Seq=DataCollatorForSeq2Seq,
    )
    trainer = train_on_responses_only(
        trainer,
        instruction_part="<|im_start|>user\n",
        response_part="<|im_start|>assistant\n",
    )
    train_result = trainer.train()
    write_json(output_paths["trainer_log_history"], trainer.state.log_history)
    write_json(output_paths["train_result"], safe_to_dict(train_result))

    print("\n=== Node 6: model inference + classification metrics ===")
    FastLanguageModel.for_inference(model)
    predictions = run_label_score_evaluation(
        model=model,
        tokenizer=tokenizer,
        records=test_records,
        labels=labels,
    )
    metrics = build_metrics(predictions, labels)
    write_json(output_paths["metrics"], metrics)
    write_jsonl(output_paths["predictions"], predictions)
    write_confusion_matrix_csv(output_paths["confusion_matrix"], metrics)
    print(json.dumps(metrics["summary"], ensure_ascii=False, indent=2))

    print("\n=== Node 7: export model adapter ===")
    model.save_pretrained(output_paths["adapter_dir"])
    tokenizer.save_pretrained(output_paths["adapter_dir"])
    report = {
        "run_id": RUN_ID,
        "model_id": MODEL_ID,
        "output_dir": output_paths["output_dir"],
        "adapter_dir": output_paths["adapter_dir"],
        "metrics_path": output_paths["metrics"],
        "predictions_path": output_paths["predictions"],
        "elapsed_seconds": round(time.time() - started_at, 2),
        "note": "PEFT adapter export only. No OpenWebUI/Ollama/GGUF export in this hardcoded demo.",
    }
    write_json(output_paths["report"], report)
    print(json.dumps(report, ensure_ascii=False, indent=2))


def run_with_logging() -> None:
    """Mirror console output to a timestamped log file for Vast.ai debugging."""
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    log_path = LOG_DIR / f"fine_tuning_hardcode_{time.strftime('%Y%m%d_%H%M%S')}.log"
    original_stdout = sys.stdout
    original_stderr = sys.stderr
    with log_path.open("w", encoding="utf-8", buffering=1) as log_file:
        sys.stdout = TeeStream(original_stdout, log_file)
        sys.stderr = TeeStream(original_stderr, log_file)
        try:
            print(f"Logging to: {log_path.as_posix()}")
            print_runtime_summary()
            main()
            print(f"\nSUCCESS. Full log saved to: {log_path.as_posix()}")
        except BaseException:
            print("\nFAILED. Full traceback:")
            traceback.print_exc()
            print(f"\nFull log saved to: {log_path.as_posix()}")
            raise
        finally:
            sys.stdout = original_stdout
            sys.stderr = original_stderr


class TeeStream:
    """Write stream output to both console and a log file."""

    def __init__(self, *streams):
        self.streams = streams

    def write(self, data: str) -> int:
        for stream in self.streams:
            stream.write(data)
            stream.flush()
        return len(data)

    def flush(self) -> None:
        for stream in self.streams:
            stream.flush()

    @property
    def encoding(self) -> str:
        return "utf-8"


def print_runtime_summary() -> None:
    """Print environment details that are useful when debugging Vast.ai runs."""
    print("=== Runtime summary ===")
    print(f"python: {sys.version}")
    print(f"cwd: {Path.cwd().as_posix()}")
    print(f"script: {Path(__file__).resolve().as_posix()}")
    print(f"run_id: {RUN_ID}")
    print(f"model_id: {MODEL_ID}")
    print(f"output_dir: {OUTPUT_DIR.as_posix()}")
    print(f"max_steps: {MAX_STEPS}")
    print(f"max_test_records: {MAX_TEST_RECORDS}")
    for name in ("CUDA_VISIBLE_DEVICES", "HF_HOME", "HF_TOKEN", "WANDB_DISABLED"):
        value = os.environ.get(name)
        if name == "HF_TOKEN" and value:
            value = "<set>"
        print(f"env {name}: {value}")
    try:
        import torch

        print(f"torch: {torch.__version__}")
        print(f"cuda_available: {torch.cuda.is_available()}")
        if torch.cuda.is_available():
            print(f"cuda_device_count: {torch.cuda.device_count()}")
            for index in range(torch.cuda.device_count()):
                props = torch.cuda.get_device_properties(index)
                total_gb = props.total_memory / (1024**3)
                print(f"cuda_device_{index}: {props.name}, vram_gb={total_gb:.2f}")
    except Exception as exc:
        print(f"torch_runtime_summary_error: {exc}")


def make_output_dirs() -> dict[str, str]:
    metrics_dir = OUTPUT_DIR / "metrics"
    artifact_dir = OUTPUT_DIR / "artifacts"
    adapter_dir = artifact_dir / "adapter"
    for path in (OUTPUT_DIR, LOG_DIR, metrics_dir, adapter_dir):
        path.mkdir(parents=True, exist_ok=True)
    return {
        "output_dir": OUTPUT_DIR.as_posix(),
        "config": (OUTPUT_DIR / "hardcoded_config.json").as_posix(),
        "trainer_log_history": (metrics_dir / "trainer_log_history.json").as_posix(),
        "train_result": (metrics_dir / "train_result.json").as_posix(),
        "metrics": (metrics_dir / "eval_metrics.json").as_posix(),
        "predictions": (metrics_dir / "predictions.jsonl").as_posix(),
        "confusion_matrix": (metrics_dir / "confusion_matrix.csv").as_posix(),
        "report": (OUTPUT_DIR / "run_report.json").as_posix(),
        "adapter_dir": adapter_dir.as_posix(),
    }


def validate_inputs() -> None:
    missing = [
        path.as_posix()
        for path in (TRAIN_JSONL, VALIDATION_JSONL, TEST_JSONL, PROMPT_TEMPLATE_JSON)
        if not path.exists()
    ]
    if missing:
        raise FileNotFoundError("Missing Phase 1-3 artifacts: " + ", ".join(missing))


def build_hardcoded_config() -> dict[str, Any]:
    return {
        "nodes": ["node4_hyperparameter_config", "node5_fine_tuning_metrics", "node6_inference", "node7_export"],
        "task_type": "classification",
        "model_id": MODEL_ID,
        "backend": "unsloth",
        "method": "qlora",
        "data": {
            "train_jsonl": TRAIN_JSONL.as_posix(),
            "validation_jsonl": VALIDATION_JSONL.as_posix(),
            "test_jsonl": TEST_JSONL.as_posix(),
            "prompt_template_json": PROMPT_TEMPLATE_JSON.as_posix(),
        },
        "model_load": {
            "max_seq_length": MAX_SEQ_LENGTH,
            "load_in_4bit": LOAD_IN_4BIT,
        },
        "lora": {
            "rank": LORA_RANK,
            "alpha": LORA_ALPHA,
            "dropout": LORA_DROPOUT,
            "target_modules": LORA_TARGET_MODULES,
        },
        "trainer": {
            "per_device_train_batch_size": PER_DEVICE_TRAIN_BATCH_SIZE,
            "per_device_eval_batch_size": PER_DEVICE_EVAL_BATCH_SIZE,
            "gradient_accumulation_steps": GRADIENT_ACCUMULATION_STEPS,
            "learning_rate": LEARNING_RATE,
            "num_train_epochs": NUM_TRAIN_EPOCHS,
            "max_steps": MAX_STEPS,
            "warmup_steps": WARMUP_STEPS,
            "weight_decay": WEIGHT_DECAY,
            "lr_scheduler_type": LR_SCHEDULER_TYPE,
            "optim": OPTIM,
            "seed": SEED,
            "eval_steps": EVAL_STEPS,
            "save_steps": SAVE_STEPS,
        },
        "inference": {
            "strategy": "constrained_label_score",
            "max_test_records": MAX_TEST_RECORDS,
        },
        "export": {
            "type": "peft_adapter",
            "openwebui": False,
            "gguf": False,
        },
    }


def import_training_libs():
    try:
        from datasets import Dataset
        from transformers import DataCollatorForSeq2Seq
        from trl import SFTConfig, SFTTrainer
        from unsloth import FastLanguageModel
    except ImportError as exc:
        raise SystemExit(
            "Missing training dependencies. On Vast.ai, install first:\n"
            "pip install unsloth trl transformers datasets accelerate bitsandbytes scikit-learn pandas"
        ) from exc
    return FastLanguageModel, Dataset, SFTConfig, SFTTrainer, DataCollatorForSeq2Seq


def to_text_rows(records: list[dict[str, Any]], tokenizer) -> list[dict[str, str]]:
    rows = []
    for record in records:
        rows.append(
            {
                "text": render_chat_text(
                    tokenizer,
                    record["messages"],
                    add_generation_prompt=False,
                )
            }
        )
    return rows


def render_chat_text(tokenizer, messages: list[dict[str, str]], *, add_generation_prompt: bool) -> str:
    """Render chat messages, disabling Qwen3 thinking when the tokenizer supports it."""
    try:
        return tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=add_generation_prompt,
            enable_thinking=False,
        )
    except TypeError:
        return tokenizer.apply_chat_template(
            messages,
            tokenize=False,
            add_generation_prompt=add_generation_prompt,
        )
    except Exception:
        return render_qwen_messages_manually(messages, add_generation_prompt=add_generation_prompt)


def render_qwen_messages_manually(
    messages: list[dict[str, str]],
    *,
    add_generation_prompt: bool,
) -> str:
    parts = []
    for message in messages:
        parts.append(f"<|im_start|>{message['role']}\n{message['content']}<|im_end|>")
    if add_generation_prompt:
        parts.append("<|im_start|>assistant\n")
    return "\n".join(parts)


def build_trainer(
    *,
    model,
    tokenizer,
    train_dataset,
    validation_dataset,
    SFTConfig,
    SFTTrainer,
    DataCollatorForSeq2Seq,
):
    sft_config = make_sft_config(SFTConfig)
    trainer_kwargs = {
        "model": model,
        "train_dataset": train_dataset,
        "eval_dataset": validation_dataset,
        "data_collator": DataCollatorForSeq2Seq(tokenizer=tokenizer),
        "args": sft_config,
    }
    trainer_init_params = inspect.signature(SFTTrainer.__init__).parameters
    if "processing_class" in trainer_init_params:
        trainer_kwargs["processing_class"] = tokenizer
    else:
        trainer_kwargs["tokenizer"] = tokenizer
    if "dataset_text_field" in trainer_init_params:
        trainer_kwargs["dataset_text_field"] = "text"
    if "max_seq_length" in trainer_init_params:
        trainer_kwargs["max_seq_length"] = MAX_SEQ_LENGTH
    if "packing" in trainer_init_params:
        trainer_kwargs["packing"] = False
    return SFTTrainer(**trainer_kwargs)


def make_sft_config(SFTConfig):
    import torch

    use_bf16 = torch.cuda.is_available() and torch.cuda.is_bf16_supported()
    kwargs = {
        "per_device_train_batch_size": PER_DEVICE_TRAIN_BATCH_SIZE,
        "per_device_eval_batch_size": PER_DEVICE_EVAL_BATCH_SIZE,
        "gradient_accumulation_steps": GRADIENT_ACCUMULATION_STEPS,
        "warmup_steps": WARMUP_STEPS,
        "num_train_epochs": NUM_TRAIN_EPOCHS,
        "learning_rate": LEARNING_RATE,
        "fp16": not use_bf16,
        "bf16": use_bf16,
        "logging_steps": LOGGING_STEPS,
        "optim": OPTIM,
        "weight_decay": WEIGHT_DECAY,
        "lr_scheduler_type": LR_SCHEDULER_TYPE,
        "seed": SEED,
        "output_dir": (OUTPUT_DIR / "checkpoints").as_posix(),
        "report_to": "none",
        "eval_steps": EVAL_STEPS,
        "save_strategy": "steps",
        "save_steps": SAVE_STEPS,
        "load_best_model_at_end": True,
        "metric_for_best_model": "eval_loss",
    }
    params = inspect.signature(SFTConfig.__init__).parameters
    if MAX_STEPS is not None:
        kwargs["max_steps"] = MAX_STEPS
    if "eval_strategy" in params:
        kwargs["eval_strategy"] = "steps"
    elif "evaluation_strategy" in params:
        kwargs["evaluation_strategy"] = "steps"
    else:
        kwargs["eval_strategy"] = "steps"
    if "dataset_text_field" in params:
        kwargs["dataset_text_field"] = "text"
    if "packing" in params:
        kwargs["packing"] = False
    if "max_seq_length" in params:
        kwargs["max_seq_length"] = MAX_SEQ_LENGTH
    elif "max_length" in params:
        kwargs["max_length"] = MAX_SEQ_LENGTH

    if any(param.kind == inspect.Parameter.VAR_KEYWORD for param in params.values()):
        return SFTConfig(**kwargs)
    filtered = {key: value for key, value in kwargs.items() if key in params}
    return SFTConfig(**filtered)


def run_label_score_evaluation(
    *,
    model,
    tokenizer,
    records: list[dict[str, Any]],
    labels: list[str],
) -> list[dict[str, Any]]:
    predictions = []
    for index, record in enumerate(records):
        messages = record["messages"]
        expected = messages[-1]["content"].strip()
        prompt_messages = messages[:-1]
        scores = score_labels(model=model, tokenizer=tokenizer, messages=prompt_messages, labels=labels)
        predicted = max(scores, key=scores.get)
        predictions.append(
            {
                "index": index,
                "expected": expected,
                "predicted": predicted,
                "correct": predicted == expected,
                "scores": scores,
                "text": messages[-2]["content"],
            }
        )
    return predictions


def score_labels(
    *,
    model,
    tokenizer,
    messages: list[dict[str, str]],
    labels: list[str],
) -> dict[str, float]:
    import torch
    import torch.nn.functional as F

    prompt_text = render_chat_text(tokenizer, messages, add_generation_prompt=True)
    prompt_ids = tokenizer(prompt_text, return_tensors="pt", add_special_tokens=False)["input_ids"]
    prompt_length = int(prompt_ids.shape[-1])

    scores: dict[str, float] = {}
    device = next(model.parameters()).device
    for label in labels:
        full_text = prompt_text + label
        encoded = tokenizer(full_text, return_tensors="pt", add_special_tokens=False)
        input_ids = encoded["input_ids"].to(device)
        if input_ids.shape[-1] <= prompt_length:
            scores[label] = -math.inf
            continue

        with torch.no_grad():
            logits = model(input_ids=input_ids).logits

        target_ids = input_ids[:, 1:]
        log_probs = F.log_softmax(logits[:, :-1, :], dim=-1)
        token_log_probs = log_probs.gather(-1, target_ids.unsqueeze(-1)).squeeze(-1)
        label_token_log_probs = token_log_probs[:, prompt_length - 1 :]
        scores[label] = float(label_token_log_probs.mean().detach().cpu())
    return scores


def build_metrics(predictions: list[dict[str, Any]], labels: list[str]) -> dict[str, Any]:
    from sklearn.metrics import classification_report, confusion_matrix

    y_true = [item["expected"] for item in predictions]
    y_pred = [item["predicted"] for item in predictions]
    report = classification_report(
        y_true,
        y_pred,
        labels=labels,
        output_dict=True,
        zero_division=0,
    )
    matrix = confusion_matrix(y_true, y_pred, labels=labels)
    correct = sum(1 for item in predictions if item["correct"])
    total = len(predictions)
    return {
        "summary": {
            "total": total,
            "correct": correct,
            "accuracy": 0.0 if total == 0 else round(correct / total, 4),
            "macro_f1": round(report.get("macro avg", {}).get("f1-score", 0.0), 4),
        },
        "labels": labels,
        "classification_report": report,
        "confusion_matrix": matrix.tolist(),
    }


def clean_prediction(text: str, labels: list[str]) -> str:
    """Kept for optional debug generation; label scoring is the default path."""
    text = re.sub(r"<think>.*?</think>", "", text or "", flags=re.DOTALL).strip()
    text = re.sub(r"<reasoning>.*?</reasoning>", "", text, flags=re.DOTALL).strip()
    text = re.sub(r"<\|.*?\|>", "", text).strip()
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    text = lines[-1] if lines else ""
    if text in labels:
        return text
    for label in labels:
        if label in text:
            return label
    return "unknown"


def read_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def read_jsonl(path: Path) -> list[dict[str, Any]]:
    records = []
    with path.open("r", encoding="utf-8") as file:
        for line in file:
            if line.strip():
                records.append(json.loads(line))
    return records


def write_json(path: str | Path, payload: Any) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    Path(path).write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")


def write_jsonl(path: str | Path, records: list[dict[str, Any]]) -> None:
    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with Path(path).open("w", encoding="utf-8") as file:
        for record in records:
            file.write(json.dumps(record, ensure_ascii=False) + "\n")


def write_confusion_matrix_csv(path: str | Path, metrics: dict[str, Any]) -> None:
    labels = metrics["labels"]
    matrix = metrics["confusion_matrix"]
    lines = ["," + ",".join(csv_escape(label) for label in labels)]
    for label, row in zip(labels, matrix):
        lines.append(csv_escape(label) + "," + ",".join(str(value) for value in row))
    Path(path).write_text("\n".join(lines) + "\n", encoding="utf-8")


def csv_escape(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def safe_to_dict(value: Any) -> dict[str, Any]:
    if hasattr(value, "_asdict"):
        return dict(value._asdict())
    if hasattr(value, "__dict__"):
        payload = {}
        for key, item in vars(value).items():
            try:
                json.dumps(item)
                payload[key] = item
            except TypeError:
                payload[key] = str(item)
        return payload
    return {"value": str(value)}


if __name__ == "__main__":
    run_with_logging()
